# Keep the source panels in GitHub and deploy the verified annual data files.
files <- rsconnect::listDeploymentFiles(".")
annual_files <- list.files("app-data", recursive = TRUE, full.names = TRUE)
source_panels <- c("MSA_analysis_data.dta", "master_county_build.dta", "State_CH_analysis_data.dta")
if (!length(annual_files) || !all(annual_files %in% files))
  stop("The deployment bundle is missing prepared app data.")
if (any(source_panels %in% files))
  stop("The deployment bundle should use annual data files instead of full panels.")
if (!all(c("app.R", "renv.lock") %in% files))
  stop("The deployment bundle is missing the app or its dependency lockfile.")
output <- Sys.getenv("APP_TEST_OUTPUT", unset = "/tmp/agglomeration-checks")
dir.create(output, recursive = TRUE, showWarnings = FALSE)
writeLines(files, file.path(output, "deployment_files.txt"))
cat("Deployment includes", length(annual_files), "prepared data files.\n")
